# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(unique=True)),
                ('status_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('stroke_color', models.CharField(choices=[('#FF0000', 'Vermelho'), ('#0000FF', 'Azul'), ('#4C1A00', 'Marrom')], default='#FF0000', max_length=10)),
                ('fill_color', models.CharField(choices=[('#FF0000', 'Vermelho'), ('#3399FF', 'Azul'), ('#993300', 'Marrom')], default='#FF0000', max_length=10)),
                ('stroke_opacity', models.FloatField(default=0.8)),
                ('fill_opacity', models.FloatField(default=0.35)),
                ('stroke_weight', models.FloatField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_orgao', models.CharField(max_length=400)),
                ('telefone_administracao', models.CharField(max_length=20)),
                ('telefone_porta_voz', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=400)),
                ('responsavel', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrgan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.Organ')),
            ],
        ),
        migrations.AddField(
            model_name='alerttype',
            name='phase_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.PhaseTypes'),
        ),
    ]
