# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorgan',
            name='user_permission',
            field=models.IntegerField(choices=[(1, 'Operacional'), (2, 'Supervisor'), (3, 'Administrador')], default=1),
        ),
    ]
