# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_userorgan_user_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('stroke_color', models.CharField(default='#FF0000', max_length=10)),
                ('fill_color', models.CharField(default='#FF0000', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='alerttype',
            name='fill_color',
        ),
        migrations.RemoveField(
            model_name='alerttype',
            name='stroke_color',
        ),
        migrations.AddField(
            model_name='alerttype',
            name='alert_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alertas.AlertColors'),
        ),
    ]
