# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_auto_20160214_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertColors',
            new_name='AlertColor',
        ),
        migrations.RenameModel(
            old_name='PhaseTypes',
            new_name='PhaseType',
        ),
    ]
