# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 00:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas', '0005_auto_20160214_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_detail_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.AlertType')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.AlertStatus')),
            ],
        ),
        migrations.CreateModel(
            name='AlertApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.Alert')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('private', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.Alert')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
