# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0008_alert_alert_organ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.Organ'),
        ),
    ]
