# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0009_auto_20160215_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertcolor',
            name='color_name',
            field=models.CharField(max_length=100, verbose_name='nome da cor'),
        ),
        migrations.AlterField(
            model_name='alertcolor',
            name='fill_color',
            field=models.CharField(default='#FF0000', max_length=10, verbose_name='cor em hexadecimal do preenchimento'),
        ),
        migrations.AlterField(
            model_name='alertcolor',
            name='stroke_color',
            field=models.CharField(default='#FF0000', max_length=10, verbose_name='cor em hexadecimal da borda'),
        ),
        migrations.AlterField(
            model_name='alertstatus',
            name='status_code',
            field=models.IntegerField(unique=True, verbose_name='código do status'),
        ),
        migrations.AlterField(
            model_name='alertstatus',
            name='status_desc',
            field=models.CharField(max_length=50, verbose_name='descrição do status'),
        ),
        migrations.AlterField(
            model_name='alerttype',
            name='alert_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alertas.AlertColor', verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='alerttype',
            name='description',
            field=models.CharField(max_length=100, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='alerttype',
            name='fill_opacity',
            field=models.FloatField(default=0.35, verbose_name='opacidade do preenchimento'),
        ),
        migrations.AlterField(
            model_name='alerttype',
            name='phase_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.PhaseType', verbose_name='fase relacionada'),
        ),
        migrations.AlterField(
            model_name='alerttype',
            name='stroke_opacity',
            field=models.FloatField(default=0.8, verbose_name='opacidade da borda'),
        ),
        migrations.AlterField(
            model_name='alerttype',
            name='stroke_weight',
            field=models.FloatField(default=2, verbose_name='grossura da borda'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='endereco',
            field=models.CharField(max_length=400, verbose_name='endereço do órgão'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='nome_orgao',
            field=models.CharField(max_length=400, verbose_name='nome do órgão'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='responsavel',
            field=models.CharField(max_length=400, verbose_name='responsável pelo órgão'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='telefone_administracao',
            field=models.CharField(max_length=20, verbose_name='telefone da administração do órgão'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='telefone_porta_voz',
            field=models.CharField(max_length=20, verbose_name='telefone do porta voz do órgão'),
        ),
        migrations.AlterField(
            model_name='phasetype',
            name='phase_type',
            field=models.CharField(max_length=50, verbose_name='fase da PNPDEC'),
        ),
    ]
