# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0010_auto_20160215_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('announcement_organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.Organ')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.AlertStatus')),
            ],
        ),
    ]
