# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0013_auto_20160215_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerticon',
            name='icon_url',
            field=models.URLField(verbose_name='url da imagem do ícone'),
        ),
    ]
