# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0015_auto_20160215_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_detail_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(max_length=500)),
                ('alert_organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.Organ')),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.AlertType')),
            ],
        ),
    ]
