# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0017_auto_20160215_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedalert',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alertas.AlertStatus'),
        ),
        migrations.AddField(
            model_name='reportedalert',
            name='visitor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reportedalert',
            name='visitor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='reportedalert',
            name='visitor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
