# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0018_auto_20160216_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedalert',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.AlertStatus'),
        ),
        migrations.AlterField(
            model_name='reportedalert',
            name='visitor_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reportedalert',
            name='visitor_name',
            field=models.CharField(max_length=150),
        ),
    ]
